version: '2'
services:

  # The Database
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

  # api:
  #   build:
  #     context: ./api
  #     args:
  #       app_env: ${APP_ENV}
  #   volumes:
  #     - ./api:/go/src/github.com/user/GoDoRP/api
  #   ports:
  #     - "5000:8080"
  #   links:
  #     - db

  frontend:
    build:
      context: ./carmudi-client
      args:
        app_env: "development"
    volumes:
      - ./carmudi-client/src:/carmudi-client/src 
    ports:
      - "3000:3000"



  volumes:
    db: