version: '2'
services:

  # The Database
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

  # api:
  #   build:
  #     context: ./carmudi-server
  #     args:
  #       app_env: "development"
  #   volumes:
  #     - ./carmudi-server:/carmudi-server
  #   ports:
  #     - "5000:80"
  #   links:
  #     - db

  php:
    build: php
    expose:
      - 9000
    volumes:
    - ./carmudi-server/www:/var/www/html

  apache2:
    image: webdevops/apache:latest
      args:
        - PHP_SOCKET=php:9000
      volumes:
        - ./carmudi-server/www:/var/www/html
      ports:
        - 5000:80
        - 443:443
      links:
        - php

  frontend:
    build:
      context: ./carmudi-client
      args:
        app_env: "development"
    volumes:
      - ./carmudi-client/src:/carmudi-client/src 
    ports:
      - "3000:3000"

volumes:
    db: